// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__List from "@rescript/core/src/Core__List.bs.mjs";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

function bopToString(op) {
  if (op === "Plus") {
    return "+";
  } else {
    return "-";
  }
}

function addBinding(ctx, name, bind) {
  return Core__List.add(ctx, [
              name,
              bind
            ]);
}

function getBinding(ctx, n) {
  var match = Core__List.get(ctx, n);
  if (match !== undefined) {
    return match[1];
  }
  
}

function pickFreshName(ctx, _name) {
  while(true) {
    var name = _name;
    var match = Core__List.getBy(ctx, (function(name){
        return function (param) {
          return name === param[0];
        }
        }(name)));
    if (match === undefined) {
      return [
              Core__List.add(ctx, [
                    name,
                    "NameBind"
                  ]),
              name
            ];
    }
    _name = match[0] + "'";
    continue ;
  };
}

function indexToName(ctx, x) {
  var match = Core__List.get(ctx, x);
  if (match !== undefined) {
    return match[0];
  } else {
    return "[" + String(x) + " bad index]";
  }
}

function printTerm(ctx, t) {
  if (typeof t !== "object") {
    if (t === "True") {
      return "true";
    } else {
      return "false";
    }
  }
  switch (t.TAG) {
    case "Int" :
        return t._0.toString();
    case "Bop" :
        return printTerm(ctx, t._1) + " " + bopToString(t._0) + " " + printTerm(ctx, t._2);
    case "Var" :
        var n = t._1;
        if (Core__List.length(ctx) === n) {
          return indexToName(ctx, t._0);
        } else {
          return "[" + String(Core__List.length(ctx)) + " " + String(n) + " bad index]";
        }
    case "Abs" :
        var match = pickFreshName(ctx, t._0);
        return "(λ" + match[1] + ". " + printTerm(match[0], t._1) + ")";
    case "App" :
        return printTerm(ctx, t._0) + " " + printTerm(ctx, t._1);
    case "If" :
        return "if " + printTerm(ctx, t._0) + " then " + printTerm(ctx, t._1) + " else " + printTerm(ctx, t._2);
    
  }
}

function printContext(ctx) {
  if (Core__List.length(ctx) === 0) {
    return "∅";
  } else {
    return Core__List.reduce(ctx, "{", (function (_acc, pair) {
                    var acc = _acc;
                    if (_acc !== "{") {
                      acc = _acc + ", ";
                    }
                    var name = pair[0];
                    if (pair[1] === "NameBind") {
                      return acc + name + ": NameBind";
                    } else {
                      return acc + name + ": VarBind}";
                    }
                  })).concat("}");
  }
}

function shift(d, t) {
  var walk = function (c, t) {
    if (typeof t !== "object") {
      if (t === "True") {
        return "True";
      } else {
        return "False";
      }
    }
    switch (t.TAG) {
      case "Int" :
          return {
                  TAG: "Int",
                  _0: t._0
                };
      case "Bop" :
          return {
                  TAG: "Bop",
                  _0: t._0,
                  _1: walk(c, t._1),
                  _2: walk(c, t._2)
                };
      case "Var" :
          var n = t._1;
          var k = t._0;
          if (k >= c) {
            return {
                    TAG: "Var",
                    _0: k + d | 0,
                    _1: n + d | 0
                  };
          } else {
            return {
                    TAG: "Var",
                    _0: k,
                    _1: n + d | 0
                  };
          }
      case "Abs" :
          return {
                  TAG: "Abs",
                  _0: t._0,
                  _1: walk(c + 1 | 0, t._1)
                };
      case "App" :
          return {
                  TAG: "App",
                  _0: walk(c, t._0),
                  _1: walk(c, t._1)
                };
      case "If" :
          return {
                  TAG: "If",
                  _0: walk(c, t._0),
                  _1: walk(c, t._1),
                  _2: walk(c, t._2)
                };
      
    }
  };
  return walk(0, t);
}

function subst(j, s, t) {
  var walk = function (c, t) {
    if (typeof t !== "object") {
      if (t === "True") {
        return "True";
      } else {
        return "False";
      }
    }
    switch (t.TAG) {
      case "Int" :
          return {
                  TAG: "Int",
                  _0: t._0
                };
      case "Bop" :
          return {
                  TAG: "Bop",
                  _0: t._0,
                  _1: walk(c, t._1),
                  _2: walk(c, t._2)
                };
      case "Var" :
          var k = t._0;
          if (k === (j + c | 0)) {
            return shift(c, s);
          } else {
            return {
                    TAG: "Var",
                    _0: k,
                    _1: t._1
                  };
          }
      case "Abs" :
          return {
                  TAG: "Abs",
                  _0: t._0,
                  _1: walk(c + 1 | 0, t._1)
                };
      case "App" :
          return {
                  TAG: "App",
                  _0: walk(c, t._0),
                  _1: walk(c, t._1)
                };
      case "If" :
          return {
                  TAG: "If",
                  _0: walk(c, t._0),
                  _1: walk(c, t._1),
                  _2: walk(c, t._2)
                };
      
    }
  };
  return walk(0, t);
}

function substTop(s, t) {
  return shift(-1, subst(0, shift(1, s), t));
}

function isVal(_ctx, t) {
  if (typeof t !== "object") {
    return true;
  }
  switch (t.TAG) {
    case "Bop" :
    case "Var" :
    case "App" :
    case "If" :
        return false;
    default:
      return true;
  }
}

var NoRuleApplies = /* @__PURE__ */Caml_exceptions.create("LambdaCompile.NoRuleApplies");

function eval1(ctx, t) {
  if (typeof t !== "object") {
    throw {
          RE_EXN_ID: NoRuleApplies,
          _1: t,
          Error: new Error()
        };
  }
  switch (t.TAG) {
    case "Bop" :
        var v2 = t._2;
        var v1 = t._1;
        var op = t._0;
        if (isVal(ctx, v1) && isVal(ctx, v2)) {
          if (op === "Plus") {
            if (typeof v1 !== "object") {
              throw {
                    RE_EXN_ID: NoRuleApplies,
                    _1: t,
                    Error: new Error()
                  };
            }
            if (v1.TAG === "Int") {
              if (typeof v2 !== "object") {
                throw {
                      RE_EXN_ID: NoRuleApplies,
                      _1: t,
                      Error: new Error()
                    };
              }
              if (v2.TAG === "Int") {
                return {
                        TAG: "Int",
                        _0: v1._0 + v2._0 | 0
                      };
              }
              throw {
                    RE_EXN_ID: NoRuleApplies,
                    _1: t,
                    Error: new Error()
                  };
            } else {
              throw {
                    RE_EXN_ID: NoRuleApplies,
                    _1: t,
                    Error: new Error()
                  };
            }
          } else {
            if (typeof v1 !== "object") {
              throw {
                    RE_EXN_ID: NoRuleApplies,
                    _1: t,
                    Error: new Error()
                  };
            }
            if (v1.TAG === "Int") {
              if (typeof v2 !== "object") {
                throw {
                      RE_EXN_ID: NoRuleApplies,
                      _1: t,
                      Error: new Error()
                    };
              }
              if (v2.TAG === "Int") {
                return {
                        TAG: "Int",
                        _0: v1._0 - v2._0 | 0
                      };
              }
              throw {
                    RE_EXN_ID: NoRuleApplies,
                    _1: t,
                    Error: new Error()
                  };
            } else {
              throw {
                    RE_EXN_ID: NoRuleApplies,
                    _1: t,
                    Error: new Error()
                  };
            }
          }
        } else {
          if (isVal(ctx, v1)) {
            var t2$p = eval1(ctx, v2);
            return {
                    TAG: "Bop",
                    _0: op,
                    _1: v1,
                    _2: t2$p
                  };
          }
          var t1$p = eval1(ctx, v1);
          return {
                  TAG: "Bop",
                  _0: op,
                  _1: t1$p,
                  _2: v2
                };
        }
    case "App" :
        var v1$1 = t._0;
        if (typeof v1$1 === "object" && v1$1.TAG === "Abs") {
          var v2$1 = t._1;
          if (isVal(ctx, v2$1)) {
            return substTop(v2$1, v1$1._1);
          }
          
        }
        var t2 = t._1;
        if (isVal(ctx, v1$1)) {
          var t2$p$1 = eval1(ctx, t2);
          return {
                  TAG: "App",
                  _0: v1$1,
                  _1: t2$p$1
                };
        }
        var t1$p$1 = eval1(ctx, v1$1);
        return {
                TAG: "App",
                _0: t1$p$1,
                _1: t2
              };
        break;
    case "If" :
        var t1 = t._0;
        if (typeof t1 !== "object") {
          if (t1 === "True") {
            return t._1;
          } else {
            return t._2;
          }
        }
        var t1$p$2 = eval1(ctx, t1);
        return {
                TAG: "If",
                _0: t1$p$2,
                _1: t._1,
                _2: t._2
              };
    default:
      throw {
            RE_EXN_ID: NoRuleApplies,
            _1: t,
            Error: new Error()
          };
  }
}

function $$eval(ctx, _t) {
  while(true) {
    var t = _t;
    console.log(printContext(ctx), "|- Term: ", printTerm(ctx, t));
    if (isVal(ctx, t)) {
      return t;
    }
    _t = eval1(ctx, t);
    continue ;
  };
}

var NoRuleApplies$1 = /* @__PURE__ */Caml_exceptions.create("LambdaCompile.Lam.NoRuleApplies");

var c = {
  contents: -1
};

function fresh(str) {
  c.contents = c.contents + 1 | 0;
  return str + c.contents.toString();
}

function go(env) {
  return function (t) {
    switch (t.TAG) {
      case "Int" :
          return {
                  TAG: "Int",
                  _0: t._0
                };
      case "Var" :
          var name$p = Belt_MapString.get(env, t._0);
          if (name$p !== undefined) {
            return {
                    TAG: "Var",
                    _0: name$p
                  };
          }
          throw {
                RE_EXN_ID: NoRuleApplies$1,
                _1: t,
                Error: new Error()
              };
      case "Lam" :
          var name = t._0;
          var name$p$1 = fresh(name);
          var env$p = Belt_MapString.set(env, name, name$p$1);
          return {
                  TAG: "Lam",
                  _0: name$p$1,
                  _1: go(env$p)(t._1)
                };
      case "App" :
          return {
                  TAG: "App",
                  _0: go(env)(t._0),
                  _1: go(env)(t._1)
                };
      case "Bop" :
          return {
                  TAG: "Bop",
                  _0: t._0,
                  _1: go(env)(t._1),
                  _2: go(env)(t._2)
                };
      case "If" :
          return {
                  TAG: "If",
                  _0: go(env)(t._0),
                  _1: go(env)(t._1),
                  _2: go(env)(t._2)
                };
      
    }
  };
}

var rename = go(undefined);

var Lam = {
  NoRuleApplies: NoRuleApplies$1,
  c: c,
  fresh: fresh,
  rename: rename
};

var ANF = {};

$$eval(/* [] */0, {
      TAG: "App",
      _0: {
        TAG: "Abs",
        _0: "x",
        _1: {
          TAG: "Bop",
          _0: "Plus",
          _1: {
            TAG: "Var",
            _0: 0,
            _1: 1
          },
          _2: {
            TAG: "Int",
            _0: 10
          }
        }
      },
      _1: {
        TAG: "Bop",
        _0: "Minus",
        _1: {
          TAG: "Int",
          _0: 25
        },
        _2: {
          TAG: "Int",
          _0: 10
        }
      }
    });

console.log("");

$$eval(/* [] */0, {
      TAG: "App",
      _0: {
        TAG: "Abs",
        _0: "x",
        _1: {
          TAG: "Abs",
          _0: "y",
          _1: {
            TAG: "Var",
            _0: 1,
            _1: 2
          }
        }
      },
      _1: {
        TAG: "Abs",
        _0: "z",
        _1: {
          TAG: "Var",
          _0: 0,
          _1: 1
        }
      }
    });

console.log("");

$$eval(/* [] */0, {
      TAG: "App",
      _0: {
        TAG: "Abs",
        _0: "x",
        _1: {
          TAG: "Abs",
          _0: "y",
          _1: {
            TAG: "App",
            _0: {
              TAG: "Var",
              _0: 0,
              _1: 2
            },
            _1: {
              TAG: "Var",
              _0: 1,
              _1: 2
            }
          }
        }
      },
      _1: {
        TAG: "Abs",
        _0: "z",
        _1: {
          TAG: "Var",
          _0: 0,
          _1: 1
        }
      }
    });

export {
  bopToString ,
  addBinding ,
  getBinding ,
  pickFreshName ,
  indexToName ,
  printTerm ,
  printContext ,
  shift ,
  subst ,
  substTop ,
  isVal ,
  NoRuleApplies ,
  eval1 ,
  $$eval ,
  Lam ,
  ANF ,
}
/* rename Not a pure module */
