// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__List from "@rescript/core/src/Core__List.mjs";

describe("Vitest bindings", (function () {
        test("basic expect assertions", (function () {
                expect(4).toBe(4);
                expect("hello").toEqual("hello");
                expect(true).toBeTruthy();
                expect(false).toBeFalsy();
              }));
        test("string operations", (function () {
                var str = "ReScript";
                expect(str.length).toBe(8);
                expect(str).toContain("Script");
              }));
        test("array operations", (function () {
                var arr = [
                  1,
                  2,
                  3,
                  4,
                  5
                ];
                expect(arr).toHaveLength(5);
                expect(arr).toContain(3);
              }));
        test("number comparisons", (function () {
                expect(10.0).toBeGreaterThan(5.0);
                expect(3.0).toBeLessThan(5.0);
                expect(3.14159).toBeCloseTo(3.14);
              }));
      }));

describe("ReScript specific tests", (function () {
        test("option type handling", (function () {
                expect(42).toBeDefined();
                expect(undefined).toBeUndefined();
              }));
        test("list operations", (function () {
                var list = {
                  hd: 1,
                  tl: {
                    hd: 2,
                    tl: {
                      hd: 3,
                      tl: /* [] */0
                    }
                  }
                };
                expect(Core__List.length(list)).toBe(3);
                expect(Core__List.head(list)).toEqual(1);
              }));
        test("pattern matching results", (function () {
                expect(42).toBe(42);
                expect(0).toBe(0);
              }));
      }));

export {
  
}
/*  Not a pure module */
